version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.27.0
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: dev_admin_secret
      HASURA_GRAPHQL_CORS_DOMAIN: "http://localhost:9695"
      HASURA_GRAPHQL_ENABLE_CONSOLE_ASSETS_DEBUG: "true"
      HASURA_GRAPHQL_LOG_LEVEL: debug
